name: Java CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Compile and run
      run: |
        javac src/PhoneFormatter.java -d .
        java PhoneFormatter > output.txt
        
    - name: Verify output
      run: |
        echo "Проверяем содержимое output.txt:"
        cat output.txt
        grep -q "+1 (900) 111-22-33" output.txt
        grep -q "+1 (915) 555-66-77" output.txt
